dRop TABLE WINE_TYPE;
dRop TABLE INVENTORY;
drop TABLE LCBO;
DROP TABLE WINE;

SELECT * FROM LCBO;
SELECT * FROM WINE;
SELECT * FROM WINE_TYPE;
SELECT * FROM INVENTORY;

--  QUE 1
SELECT LCBOCity, COUNT(LCBOCity) AS 'Number Of Stores'
FROM LCBO
GROUP BY LCBOCity 
ORDER BY LCBOCity;

-- QUE 2
SELECT wineName, wineYear, LCBOAdd, InvQTY
FROM LCBO
INNER JOIN INVENTORY ON LCBO.LCBO_ID = INVENTORY.LCBO_ID
INNER JOIN WINE ON INVENTORY.wineID  = WINE.wineID
GROUP BY wineYear, wineName, LCBOAdd, InvQTY
ORDER BY InvQTY DESC;


-- QUE 3
SELECT DISTINCT wtName, LCBOAdd, SUM(invQTY) AS 'Total In Stock'
FROM LCBO
INNER JOIN INVENTORY ON LCBO.LCBO_ID = INVENTORY.LCBO_ID
INNER JOIN WINE ON INVENTORY.wineID  = WINE.wineID
INNER JOIN WINE_TYPE ON WINE.wtCode = WINE_TYPE.wtCode
GROUP BY wtName, LCBOAdd, invQTY
ORDER BY wtName;


-- QUE 4
SELECT wineName
FROM LCBO
INNER JOIN INVENTORY ON LCBO.LCBO_ID = INVENTORY.LCBO_ID
INNER JOIN WINE ON INVENTORY.wineID = WINE.wineID
WHERE WINE.wineID NOT IN
(SELECT wineID FROM LCBO)
GROUP BY wineName;



--QUE 5
 SELECT LCBOAdd, LCBOPhone
 FROM LCBO
	INNER JOIN INVENTORY ON LCBO.LCBO_ID = INVENTORY.LCBO_ID
	INNER JOIN WINE ON INVENTORY.wineID = WINE.wineID
	WHERE LCBOHasTastingBar = 1 AND LCBOHasVintages = 1 AND wineName LIKE '%Cabernet Franc%';

--QUE 6

SELECT  DISTINCT LCBOCity
FROM LCBO
inner join INVENTORY ON LCBO.LCBO_ID = INVENTORY.LCBO_ID
INNER JOIN WINE ON INVENTORY.wineID = WINE.wineID
WHERE	
		wtCode = 'D'
		AND
		winePrice > 30;


-- QUE 7
SELECT LCBOAdd
FROM LCBO
inner join INVENTORY ON LCBO.LCBO_ID = INVENTORY.LCBO_ID
INNER JOIN WINE ON INVENTORY.wineID = WINE.wineID
WHERE winePrice = (SELECT MAX(winePrice) FROM WINE);
	