IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'EMPLOYEE'))
BEGIN
    DROP TABLE EMPLOYEE;
END

CREATE TABLE EMPLOYEE
(empNo		CHAR(3),
 empFirst	VARCHAR(25),
 empLast	VARCHAR(25),
 empTitle	VARCHAR(25),
 empSalary	DECIMAL(8,2),
 empStart	DATE,

 CONSTRAINT pk_employee_empNo PRIMARY KEY(empNo)
);