--1
SELECT movName, ftName
FROM MOVIE
	JOIN MOVIE_FORMAT ON MOVIE.movID = MOVIE_FORMAT.movID
	JOIN FORMAT_TYPE ON MOVIE_FORMAT.ftID = FORMAT_TYPE.ftID;


--2
SELECT movName, dirFName AS 'Director', movRunTime, movNumDisks
FROM MOVIE
	LEFT JOIN DIRECTOR ON MOVIE.dirID = DIRECTOR.dirID
-- OR RIGHT JOIN MOVIE ON DIRECTOR.movID = MOVIE.movID
ORDER BY movName;
--SHOWS THE NULL

--3
SELECT boxset.movName, DVD.movName
FROM MOVIE AS boxset
	INNER JOIN MOVIE AS DVD ON boxset.movID = DVD.boxSetID
WHERE boxset.boxSetID IS NULL;
--BECAUSE OF THE RECURSION TO AVOID DUPLICATES WE 'AS' THE REPETITIVE, ALSO SPECIFY THE BOXSET ID WITH THE .boxsetid

--4
SELECT DVD.movName
FROM MOVIE AS boxset
	INNER JOIN MOVIE AS DVD ON boxset.movID = DVD.boxSetID
	JOIN MOVIE_FORMAT ON boxset.movID = MOVIE_FORMAT.movID
	JOIN FORMAT_TYPE ON MOVIE_FORMAT.ftID = FORMAT_TYPE.ftID
WHERE boxset.movName LIKE 'Lord of the%'
	AND boxset.boxSetID IS NULL
	AND FORMAT_TYPE.ftName = 'NTSC';
	